# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: be6948349080c3e934334acb2e582cac06c674a33a342e374f8c88b7d82d61508af52dc43ace46671ce4d2d5310ac916aaab1efd94e7c701047ec995ee3b2e7c

test:
  secret_key_base: 656f8a0be3273b60ddce8391a37aa5ed248aceb3d854eddf988121ce5b1cc71117f3bf69fc6e2cfd15e03d336c9c8aa291517f2b1006ce2d744a5bb63c640317

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
